### ISSUE TITLE
在codeigniter 2.2.1中调用提示 Class 'Wx_Controller' not found

### ISSUE THREAD

**Issue by dolphin836** [SevenOutman/CodeIgniter-Weixin_Template#1]
看了扩展核心系统类的文档，应该是不需要加载的啊，为什么会提示  Class 'Wx_Controller' not found，是版本的问题么，还是有什么问题没有拷贝过来？

**Comment by SevenOutman** [comment]
@dolphin836 这个仓库本身就是扩展过的 CI 框架，而不是把里面的东西拿出来放到自己的 CI 框架里用
